#!/usr/bin/env bash

original_dir=$PWD

# if DRYRUN=1 then don't actually run the commands
run() {
    if [[ "$DRYRUN" == "1" ]]; then
        echo "$@"
    else
        "$@"
    fi
}

echo "Are you on a steam deck and is this the first time you are running this script?"
read -r -p "(y/n) " answer
if [[ "$answer" == "y" ]]; then
    echo "To enable dev-mode, first run 'passwd' to set a password, then run 'sudo steamos-devmode enable'"
    echo "After completing run this script again."
fi

if [[ ! -f "$XDG_CONFIG_HOME/package-installer/packages.list" ]]; then
    echo "No packages file found."
    echo "Please create a file called 'packages.list' in $XDG_CONFIG_HOME/package-installer"
    exit 1
fi

packages=$(cat "$XDG_CONFIG_HOME/package-installer/packages.list")

if [[ -z "yay" ]]; then
    echo "yay not found. Installing..."
    run cd /tmp
    run git clone https://aur.archlinux.org/yay-bin.git
    run cd yay-bin
    run makepkg -si
    run cd $original_dir
fi

run yay -Syu --needed $packages
